---
title: "Lab 04 - La Quinta is Spanish for next to Denny's, Pt. 1"
author: "Insert your name here"
date: "Insert date here"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox)
```



```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
```

### Exercise 1,2
```{r}
 dennys <- dennys
 laquinta <- laquinta 

dim(dennys)
dim(laquinta)

# View(dennys)
# View(laquinta)

str(dennys)
str(laquinta)

glimpse(dennys)
glimpse(laquinta)

table(laquinta$state)
```

### Exercise 3

denny - no
laQuinta -yes 
...

### Exercise 4

state, address, latitude, etc. 

...

### Exercise 5

```{r}
dennys%>%
  filter(!(state %in% states$abbreviation))%>%
  print()


```
...

### Exercise 6
```{r}
dennys <- dennys %>%
  dplyr::mutate(country ="United States")


```
...

### Exercise 7

```{r}
laquinta %>%
  filter(!(state %in% states$abbreviation)) %>%
  print() 


```
## Exercise8

```{r}
laquinta<-laquinta %>%
  mutate(country = case_when(
    state %in% state.abb     ~ "United States",
    state %in% c("ON", "BC") ~ "Canada",
    state == "ANT"           ~ "Colombia",
    state == "FM"            ~ "Hondoras",
    state == "AG"           ~  "Mexico"))  

laquinta<-laquinta%>%
  filter(country=="United States")
```

## Exercise 9

```{r}
sort(table(dennys$state))
sort(table(laquinta$state))

```

DE
ME
Actually, I am not familiar with that states..

## Exercise10
```{r}
dennys %>%
  count(state) %>%
  inner_join(states,by=c("state" = "abbreviation"
  )) %>%
 dplyr::mutate(den_per_sq = 1000*area/n) %>%
  arrange(den_per_sq)

laquinta %>%
  count(state)%>%
  inner_join(states,by=c("state"="abbreviation"
  )) %>%
 dplyr::mutate(den_per_sq = 1000*area/n) %>%
  arrange(den_per_sq)


dennys <- dennys %>%
  mutate(establishment="dn")

laquinta <- laquinta%>%
  mutate(establishment = "lq")

dn_lq<-bind_rows(dennys,laquinta)

ggplot(dn_lq, mapping = aes(x = longitude, y = latitude, color = establishment)) +
  geom_point()

```

## Exercise 11 

```{r}

dn_lqNC <- dn_lq %>%
  filter(state == "NC")

ggplot(dn_lqNC, mapping = aes(x = longitude, y = latitude, color = establishment)) +
  geom_point(alpha=0.5)

```

## Exercise 12 

```{r}

dn_lqTX<- dn_lq %>%
  filter(state == "TX")


ggplot(dn_lqTX, mapping = aes(x = longitude, y = latitude, color = establishment)) +
  geom_point(alpha=0.5)
```
